FROM jenkins/jenkins:2.414.3-alpine-jdk11
USER root

RUN apk add docker

USER jenkins
RUN jenkins-plugin-cli --plugins github-pullrequest:0.5.0
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"
RUN jenkins-plugin-cli --plugins docker-plugin:1.5