void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/nahid111/jenkins-practice"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}

pipeline {
    agent any

    triggers {
        githubPush()
    }
    
    stages {
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                cd app
                go test -v
                '''
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                cd app
                go build server.go
                ls
                '''
            }
        }
    }
}
